imported pandas for data manipulation,
load weather dataset to a variable "data" and display it using display()

In [12]:
import pandas as pd
data=pd.read_csv('/content/weather_history_processed.csv')
display(data)

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Summary_Drizzle,Summary_Dry,Summary_Dry and Mostly Cloudy,...,Summary_Foggy,Summary_Humid and Mostly Cloudy,Summary_Humid and Overcast,Summary_Humid and Partly Cloudy,Summary_Light Rain,Summary_Mostly Cloudy,Summary_Overcast,Summary_Partly Cloudy,Summary_Rain,Precip Type_snow
0,-0.307028,-0.379605,0.867470,0.681763,0.600679,0.983,-0.243970,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,-0.319345,-0.394856,0.831325,0.706583,0.675253,0.983,-0.169559,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,-0.316999,-0.191336,0.867470,-1.063971,0.162560,0.929,-0.123424,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,-0.431964,-0.516337,0.795181,0.679005,0.768470,0.983,-0.053477,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-0.382693,-0.418521,0.795181,0.155009,0.675253,0.983,-0.038595,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88618,1.439725,1.383713,0.313253,0.146735,-1.450093,1.000,-0.358564,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88619,1.288395,1.248033,0.373494,-0.007706,-1.552631,0.966,-0.239505,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88620,1.019754,1.007174,0.469880,-0.197999,-1.459414,1.000,-0.165094,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88621,0.965204,0.958266,0.518072,0.066757,-1.552631,1.000,-0.121936,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88622,0.850827,0.855717,0.530120,-0.730268,-1.375519,0.964,-0.090683,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [18]:
data.shape

(88623, 21)

for dataset shape

In [13]:
data.head()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Summary_Drizzle,Summary_Dry,Summary_Dry and Mostly Cloudy,...,Summary_Foggy,Summary_Humid and Mostly Cloudy,Summary_Humid and Overcast,Summary_Humid and Partly Cloudy,Summary_Light Rain,Summary_Mostly Cloudy,Summary_Overcast,Summary_Partly Cloudy,Summary_Rain,Precip Type_snow
0,-0.307028,-0.379605,0.867470,0.681763,0.600679,0.983,-0.243970,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,-0.319345,-0.394856,0.831325,0.706583,0.675253,0.983,-0.169559,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,-0.316999,-0.191336,0.867470,-1.063971,0.162560,0.929,-0.123424,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,-0.431964,-0.516337,0.795181,0.679005,0.768470,0.983,-0.053477,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-0.382693,-0.418521,0.795181,0.155009,0.675253,0.983,-0.038595,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

first 5 rows are shown using head() ,the default argument value is 5

In [14]:
data.tail()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Summary_Drizzle,Summary_Dry,Summary_Dry and Mostly Cloudy,...,Summary_Foggy,Summary_Humid and Mostly Cloudy,Summary_Humid and Overcast,Summary_Humid and Partly Cloudy,Summary_Light Rain,Summary_Mostly Cloudy,Summary_Overcast,Summary_Partly Cloudy,Summary_Rain,Precip Type_snow
88618,1.439725,1.383713,0.313253,0.146735,-1.450093,1.000,-0.358564,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88619,1.288395,1.248033,0.373494,-0.007706,-1.552631,0.966,-0.239505,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88620,1.019754,1.007174,0.469880,-0.197999,-1.459414,1.000,-0.165094,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88621,0.965204,0.958266,0.518072,0.066757,-1.552631,1.000,-0.121936,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
88622,0.850827,0.855717,0.530120,-0.730268,-1.375519,0.964,-0.090683,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

last 5 rows are shown using tail() ,the default argument value is 5

In [15]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88623 entries, 0 to 88622
Data columns (total 21 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Temperature (C)                  88623 non-null  float64
 1   Apparent Temperature (C)         88623 non-null  float64
 2   Humidity                         88623 non-null  float64
 3   Wind Speed (km/h)                88623 non-null  float64
 4   Wind Bearing (degrees)           88623 non-null  float64
 5   Visibility (km)                  88623 non-null  float64
 6   Pressure (millibars)             88623 non-null  float64
 7   Summary_Drizzle                  88623 non-null  float64
 8   Summary_Dry                      88623 non-null  float64
 9   Summary_Dry and Mostly Cloudy    88623 non-null  float64
 10  Summary_Dry and Partly Cloudy    88623 non-null  float64
 11  Summary_Foggy                    88623 non-null  float64
 12  Summary_Humid and Mostly Cloudy  88623 non-null  float64
 13  Summary_Humid and Overcast       88623 non-null  float64
 14  Summary_Humid and Partly Cloudy  88623 non-null  float64
 15  Summary_Light Rain               88623 non-null  float64
 16  Summary_Mostly Cloudy            88623 non-null  float64
 17  Summary_Overcast                 88623 non-null  float64
 18  Summary_Partly Cloudy            88623 non-null  float64
 19  Summary_Rain                     88623 non-null  float64
 20  Precip Type_snow                 88623 non-null  float64
dtypes: float64(21)
memory usage: 14.2 MB

 range index, column names , non null counts, data type, memory usage etc are shown

In [24]:
data.isnull().sum()

Temperature (C)                    0
Apparent Temperature (C)           0
Humidity                           0
Wind Speed (km/h)                  0
Wind Bearing (degrees)             0
Visibility (km)                    0
Pressure (millibars)               0
Summary_Drizzle                    0
Summary_Dry                        0
Summary_Dry and Mostly Cloudy      0
Summary_Dry and Partly Cloudy      0
Summary_Foggy                      0
Summary_Humid and Mostly Cloudy    0
Summary_Humid and Overcast         0
Summary_Humid and Partly Cloudy    0
Summary_Light Rain                 0
Summary_Mostly Cloudy              0
Summary_Overcast                   0
Summary_Partly Cloudy              0
Summary_Rain                       0
Precip Type_snow                   0
dtype: int64

check for null value count using isnull() and 0 null values

In [23]:
data.duplicated().sum()

np.int64(42)

check for duplicate values using duplicated() and found 42 duplicates

In [20]:
data.columns

Index(['Temperature (C)', 'Apparent Temperature (C)', 'Humidity',
       'Wind Speed (km/h)', 'Wind Bearing (degrees)', 'Visibility (km)',
       'Pressure (millibars)', 'Summary_Drizzle', 'Summary_Dry',
       'Summary_Dry and Mostly Cloudy', 'Summary_Dry and Partly Cloudy',
       'Summary_Foggy', 'Summary_Humid and Mostly Cloudy',
       'Summary_Humid and Overcast', 'Summary_Humid and Partly Cloudy',
       'Summary_Light Rain', 'Summary_Mostly Cloudy', 'Summary_Overcast',
       'Summary_Partly Cloudy', 'Summary_Rain', 'Precip Type_snow'],
      dtype='object')

to retrieve column names

In [21]:
data['Apparent Temperature (C)'].unique()

array([-0.3796053 , -0.39485618, -0.1913357 , ...,  1.45365672,
       -0.05618127, -0.20500891])

for retrieve unique values in a specific column

In [22]:
data['Humidity'].value_counts()

Humidity
0.915663    5223
0.951807    3587
0.903614    3429
1.000000    2652
0.867470    2609
            ...
0.060241      48
0.036145      42
0.024096      35
0.012048      24
0.000000      13
Name: count, Length: 84, dtype: int64

for retrieve values counts in a specific column

In [19]:
data.describe()

,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Summary_Drizzle,Summary_Dry,Summary_Dry and Mostly Cloudy,...,Summary_Foggy,Summary_Humid and Mostly Cloudy,Summary_Humid and Overcast,Summary_Humid and Partly Cloudy,Summary_Light Rain,Summary_Mostly Cloudy,Summary_Overcast,Summary_Partly Cloudy,Summary_Rain,Precip Type_snow
count,8.862300e+04,8.862300e+04,88623.000000,8.862300e+04,8.862300e+04,88623.000000,8.862300e+04,88623.000000,88623.000000,88623.000000,...,88623.00000,88623.000000,88623.000000,88623.000000,88623.000000,88623.000000,88623.000000,88623.000000,88623.000000,88623.000000
mean,8.851418e-17,8.081729e-17,0.679745,-6.510282e-17,2.661839e-17,0.650762,2.525220e-14,0.000417,0.000339,0.000158,...,0.07102,0.000440,0.000079,0.000192,0.000632,0.301028,0.169426,0.346603,0.000113,0.100730
std,1.000006e+00,1.000006e+00,0.236334,1.000006e+00,1.000006e+00,0.257737,1.000006e+00,0.020429,0.018396,0.012568,...,0.25686,0.020973,0.008887,0.013849,0.025130,0.458707,0.375129,0.475891,0.010622,0.300973
min,-3.070863e+00,-3.201020e+00,0.000000,-1.736892e+00,-1.739065e+00,0.000000,-2.718890e+00,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-7.792026e-01,-8.008454e-01,0.518072,-7.826679e-01,-6.857140e-01,0.553500,-6.576969e-01,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,-5.539913e-03,8.791333e-02,0.734940,-8.216823e-02,-6.116072e-02,0.624000,-3.115382e-02,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.036020e-01,7.237176e-01,0.867470,6.293629e-01,9.549036e-01,0.926000,6.147362e-01,0.000000,0.000000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
max,2.808739e+00,2.645330e+00,1.000000,2.821872e+00,1.607422e+00,1.000000,2.671464e+00,1.000000,1.000000,1.000000,...,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

statistical data exploration like standard deviation,mean,count,minimum and maximum values, etc to describe the numerical data statisticaly